### ISSUE TITLE
Cli Error since version 0.6.1: `Flag keys may not contain '-': print-config`

### ISSUE THREAD

**Issue by DerZyklop** [linthtml/linthtml#304] opened 2021-02-15 10:15 UTC
I can not lint with version 0.6.1. I get 

`Flag keys may not contain '-': print-config`

No matter if i run `npx linthtml './src/**/*.html'` or `npx linthtml --version` or even `npx linthtml`.

Everything works fine with 0.6.0

Some cli output:
![Screenshot 2021-02-15 at 11 09 49](https://user-images.githubusercontent.com/912344/107933410-ff9d6680-6f7e-11eb-95b6-5c96b1c9f8ff.png)

**Comment by sylvaindumont** [comment] 2021-02-15 10:21
It is caused by meow 9.0.0 https://github.com/sindresorhus/meow/releases/tag/v9.0.0 which now forbids snakecase.
It can be fixed by forcing meow 8.1.1 in yarn resolutions or by pining it in linthtml.
The correct fix is to change print-config flag to camel case in linthtml but it could be a breaking change for some users.

**Comment by KamiKillertO** [comment] 2021-02-15 13:18
My bad I've updated meow without really looking at the changelog 🤦

**Comment by KamiKillertO** [comment] 2021-02-15 13:25
@DerZyklop @sylvaindumont I've just released LintHTML 0.6.2 with a fix.

**Closed** 2021-02-15 14:24 UTC
